apiVersion: v1
kind: Service
metadata:
  name: k8s-monitor-service
  namespace: {{.Release.Namespace}}
spec:
  selector:
    name: k8s-monitor
    type: {{ .Values.service.type }}
  ports:
    - name: "k8s-monitor"
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
status:
  loadBalancer: {}