apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-monitor
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitor
  template: 
    metadata: 
      labels: 
        app: k8s-monitor
    spec:
      serviceAccountName: k8s-monitor-sa
      containers:
      - name: appd-infra-agent
        image: sashaz/mak8s@sha256:8f92c7992de5daebff19e0daf85113867e99ce0d4e3870ed1cdf911101f70e0d #<image reference>
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: ma-config
        - secretRef:
            name: appd-secret
        resources:
          limits:
            cpu: "0.6"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1G"
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: ma-config-volume
          mountPath: /opt/appdynamics/MachineAgent/conf/logging/log4j.xml
          subPath: log4j.xml
        - name: config-volume
          mountPath: /opt/appdynamics/MachineAgent/monitors/KubernetesSnapshotExtension/config.yml
          subPath: config.yml
#        - name: truststore-volume
#          mountPath: /opt/appdynamics/MachineAgent/conf/truststore.jks
#          subPath: truststore.jks
      restartPolicy: Always
      volumes:
      - name: ma-config-volume
        configMap:
          name: ma-log-config
      - name: config-volume
        configMap:
          name: k8sext-config
      - name: truststore-volume
        secret:
          secretName: appd-truststore-secret
          items:
          - key: TRUSTSTORE_JKS
            path: truststore.jks
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-monitor-service
spec:
  selector:
    name: k8s-monitor
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}
