# Number of Threads for the Extension
numberOfThreads: 1

# This will create it in specific Tier aka Component. Replace <COMPONENT_ID>.
# Please make sure to have a trailing |.
# To find out the COMPONENT_ID, please see the screen shot here https://docs.appdynamics.com/display/latest/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|KubernetesEvents|"
metricPrefix:  "Custom Metrics|KubernetesEvents|"

# Path to your kubectl Client configuration
kubeClientConfig: "/home/origin/.kube/config"
# Events API Key obtained from AppDynamics --> Analytics --> Configuration API Keys --> Add
# The API Key you create needs to be able to Manage and Publish Custom Analytics Events
eventsApiKey: "fec1794f-4db0-4d5e-80c7-d9a3b950fe59"
# Global Account Name obtained from
# AppDynamics --> Settings --> License --> Accounts --> Global Account Name
accountName: "customer1_f569566d-7308-4ce3-9686-c4f004b9232b"

podsSchemaName: "k8s_pod_snapshots"

podsSecuritySchemaName: "openshift_pod_sec_snapshots"

deploySchemaName: "openshift_deploy_snapshots"

daemonSchemaName: "openshift_daemon_snapshots"

rsSchemaName: "openshift_rs_snapshots"

endpointSchemaName: "k8s_endpoint_snapshots"

summarySchemaName: "openshift_cluster_summary"

includePodSnapshot: "true"

includePodSecuritySnapshot: "true"

includeDeploySnapshot: "true"

includeDaemonSnapshot: "true"

includeEndpointSnapshot: "true"

includeRSSnapshot: "true"

includeSummary: "true"

logPayloads: "false"

# Events Service Endpoint. These Default settings are for SaaS Users. Change if you are on Premise
#eventsUrl: "https://fra-ana-api.saas.appdynamics.com:443"
eventsUrl: "https://analytics.api.appdynamics.com"


podsSchemaDefinition: '{
   "schema" : {
      "batch_ts": "integer",
      "deletionGracePeriod": "integer",
      "object_uid": "string",
      "clusterName": "string",
      "creationTimestamp": "date",
      "deletionTimestamp": "date",
      "generateName": "string",
      "generation": "string",
      "labels": "string",
      "name": "string",
      "namespace": "string",
      "resourceVersion": "string",
      "selfLink": "string",
      "activeDeadlineSeconds": "integer",
      "containerCount": "integer",
      "initContainerCount": "integer",
      "dnsPolicy": "string",
      "hostIPC": "boolean",
      "hostNetwork": "boolean",
      "hostPID": "boolean",
      "hostname": "string",
      "nodeName": "string",
      "priority": "integer",
      "restartPolicy": "string",
      "schedulerName": "string",
      "serviceAccountName": "string",
      "terminationGracePeriodSeconds": "integer",
      "tolerationsCount": "integer",
      "volumesCount": "integer",
      "hasNodeAffinity": "boolean",
      "hasPodAffinity": "boolean",
      "hasPodAntiAffinity": "boolean",
      "hostIP": "string",
      "phase": "string",
      "podIP": "string",
      "qosClass": "string",
      "reason": "string",
      "startTime": "date",
      "lastProbeTimeCondition": "date",
      "lastTransitionTimeCondition": "date",
      "reasonCondition": "string",
      "statusCondition": "string",
      "typeCondition": "string",
      "messageCondition": "string",
      "limitsDefined": "boolean",
      "numPorts": "integer",
      "liveProbes": "integer",
      "readyProbes": "integer"
   }
}'

deploySchemaDefinition: '{
  "schema": {
    "batch_ts": "integer",
    "deletionGracePeriod": "integer",
    "clusterName": "string",
    "name": "string",
    "namespace": "string",
    "object_uid": "string",
    "creationTimestamp": "date",
    "deletionTimestamp": "date",
    "resourceVersion": "string",
    "minReadySecs": "integer",
    "progressDeadlineSecs": "integer",
    "replicas": "integer",
    "revisionHistoryLimits": "integer",
    "strategy": "string",
    "maxSurge": "string",
    "maxUnavailable": "string",
    "replicasAvailable": "integer",
    "replicasUnAvailable": "integer",
    "replicasUpdated": "integer",
    "collisionCount": "integer",
    "replicasReady": "integer"
  }
}'

daemonSchemaDefinition: '{
  "schema": {
    "batch_ts": "integer",
    "deletionGracePeriod": "integer",
    "clusterName": "string",
    "name": "string",
    "namespace": "string",
    "object_uid": "string",
    "creationTimestamp": "date",
    "deletionTimestamp": "date",
    "resourceVersion": "string",
    "minReadySecs": "integer",
    "revisionHistoryLimits": "integer",
    "replicasAvailable": "integer",
    "replicasUnAvailable": "integer",
    "collisionCount": "integer",
    "replicasReady": "integer",
    "numberScheduled": "integer",
    "desiredNumber": "integer",
    "missScheduled": "integer",
    "updatedNumberScheduled": "integer"
  }
}'


rsSchemaDefinition: '{
  "schema": {
    "batch_ts": "integer",
    "deletionGracePeriod": "integer",
    "clusterName": "string",
    "name": "string",
    "namespace": "string",
    "object_uid": "string",
    "creationTimestamp": "date",
    "deletionTimestamp": "date",
    "resourceVersion": "string",
    "minReadySecs": "integer",
    "replicas": "integer",
    "rsReplicasAvailable": "integer",
    "replicasLabeled": "integer",
    "replicasReady": "integer"
  }
}'



endpointSchemaDefinition: '{
  "schema": {
    "batch_ts": "integer",
    "name": "string",
    "namespace": "string",
    "object_uid": "string",
    "creationTimestamp": "date",
    "deletionTimestamp": "date",
    "ip_up": "integer",
    "ip_down": "integer",
    "downContext": "string"
  }
}'


podSecuritySchemaDefinition: '{
  "schema": {
    "batch_ts": "integer",
    "clusterName": "string",
    "name": "string",
    "namespace": "string",
    "object_uid": "string",
    "creationTimestamp": "date",
    "deletionTimestamp": "date",
    "privileged": "boolean",
    "runAsUser": "string"
  }
}'




summarySchemaDefinition: '{
  "schema": {
    "batch_ts": "integer",
    "namespace": "string",
    "nodename": "string",
    "pods": "integer",
    "containers": "integer",
    "initcontainers": "integer",
    "evictions": "integer",
    "limits": "integer",
    "rprobe": "integer",
    "lprobe": "integer",
    "endpoints": "integer",
    "endpoints_healthy": "integer",
    "ip_up": "integer",
    "ip_down": "integer",
    "deploys": "integer",
    "deployReplicas": "integer",
    "deployReplicasAvailable": "integer",
    "deployReplicasUnAvailable": "integer",
    "deployCollisionCount": "integer",
    "deployReplicasReady": "integer",
    "daemons": "integer",
    "daemonReplicasAvailable": "integer",
    "daemonReplicasUnAvailable": "integer",
    "daemonCollisionCount": "integer",
    "daemonReplicasReady": "integer",
    "daemonNumberScheduled": "integer",
    "daemonDesiredNumber": "integer",
    "daemonMissScheduled": "integer",
    "rs": "integer",
    "rsReplicas": "integer",
    "rsReplicasAvailable": "integer",
    "privilegedPods": "integer"
  }
}'