apiVersion: v1
entries:
  k8s-extension:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-11-27T18:35:18.368514+05:30"
    description: Sophisticated helm chart to deploy k8s extension and machine agent
      in addition
    digest: cab88d2435354438f5cf4490d343dd9155715dc069433dbc4430a4500f9fc2fe
    home: https://appdynamics.com
    icon: https://raw.githubusercontent.com/CiscoDevNet/appdynamics-charts/master/logo.png
    keywords:
    - appdynamics
    - cluster
    - kubernetes
    - openshift
    - monitoring
    - pod
    - deployment
    - extension
    maintainers:
    - email: support@appdynamics.com
      name: AppDynamics
    name: k8s-extension
    urls:
    - https://AppdAgensts.github.io/k8s-extension-charts/k8s-extension-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-11-27T18:35:18.36788+05:30"
    description: Sophisticated helm chart to deploy k8s extension and machine agent
      in addition
    digest: 9dcabcaba65013e1ec81b49fcd42eb4277f8a28e003221e6d0158d3b18d14aac
    home: https://appdynamics.com
    icon: https://raw.githubusercontent.com/CiscoDevNet/appdynamics-charts/master/logo.png
    keywords:
    - appdynamics
    - cluster
    - kubernetes
    - openshift
    - monitoring
    - pod
    - deployment
    - extension
    maintainers:
    - email: support@appdynamics.com
      name: AppDynamics
    name: k8s-extension
    urls:
    - https://AppdAgensts.github.io/k8s-extension-charts/k8s-extension-1.0.0.tgz
    version: 1.0.0
generated: "2024-11-27T18:35:18.366674+05:30"
