{{ $secret := (lookup "v1" "Secret" .Release.Namespace "app-secret") }}
{{ $annotations := dict "temp" "temp" }}
{{ if $secret }}
  {{ $annotations = $secret.metadata.annotations }}
{{ end }}
{{ if or (not ($secret)) (get $annotations "appdynamics.helm.charts/created-by") }}
{{ $namespace := .Release.Namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: appd-secret
  namespace: {{ $namespace }}
  annotations:
    appdynamics.helm.charts/created-by: k8s-extension-helm-chart
type: Opaque
data:
  {{ with .Values.controllerInfo -}}
  ACCOUNT_ACCESS_KEY: {{ include "sensitiveData" (dict "data" .accessKey "message" "AppDynamics controller access key is required!") }}
  EVENT_ACCESS_KEY: {{ include "sensitiveData" (dict "data" .eventsApiKey "message" "AppDynamics controller events Api Key is required!") }}
  REST_API_CREDENTIALS: {{ include "sensitiveData" (dict "data" .controllerAPIUser "message" "AppDynamics controller API User is required!") }}
  {{- end -}}
{{ end -}}